# Generated by Django 3.2.8 on 2021-10-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': ('libros',)},
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='Tipo',
            new_name='tipo',
        ),
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('nombre', 'tipo')},
        ),
    ]
