# Generated by Django 3.2.8 on 2021-10-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20211010_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progenitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.CharField(max_length=50)),
                ('madre', models.CharField(max_length=50)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.persona')),
            ],
            options={
                'verbose_name': 'Progenitores',
            },
        ),
    ]
